[workspace]
members = [
    "xibalba-proto",
    "xibalba-client",
    "examples/tcp-rustls",
]
resolver = "2"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
